// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_header.proto

package com.zirtia.protocol;

public final class RPCHeader {
  private RPCHeader() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code codec.ResCode}
   */
  public enum ResCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RES_SUCCESS = 0;</code>
     */
    RES_SUCCESS(0),
    /**
     * <code>RES_FAIL = 1;</code>
     */
    RES_FAIL(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>RES_SUCCESS = 0;</code>
     */
    public static final int RES_SUCCESS_VALUE = 0;
    /**
     * <code>RES_FAIL = 1;</code>
     */
    public static final int RES_FAIL_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ResCode valueOf(int value) {
      return forNumber(value);
    }

    public static ResCode forNumber(int value) {
      switch (value) {
        case 0: return RES_SUCCESS;
        case 1: return RES_FAIL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResCode>() {
            public ResCode findValueByNumber(int number) {
              return ResCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return RPCHeader.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResCode[] VALUES = values();

    public static ResCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:codec.ResCode)
  }

  public interface RequestHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:codec.RequestHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 服务名或接口名
     * </pre>
     *
     * <code>optional string service_name = 1;</code>
     */
    String getServiceName();
    /**
     * <pre>
     * 服务名或接口名
     * </pre>
     *
     * <code>optional string service_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <pre>
     * 方法名
     * </pre>
     *
     * <code>optional string method_name = 2;</code>
     */
    String getMethodName();
    /**
     * <pre>
     * 方法名
     * </pre>
     *
     * <code>optional string method_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>optional uint64 call_id = 3;</code>
     */
    long getCallId();

    /**
     * <pre>
     * 用户自定义参数
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_param = 5;</code>
     */
    int getCustomParamCount();
    /**
     * <pre>
     * 用户自定义参数
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_param = 5;</code>
     */
    boolean containsCustomParam(
            String key);
    /**
     * Use {@link #getCustomParamMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getCustomParam();
    /**
     * <pre>
     * 用户自定义参数
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_param = 5;</code>
     */
    java.util.Map<String, String>
    getCustomParamMap();
    /**
     * <pre>
     * 用户自定义参数
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_param = 5;</code>
     */

    String getCustomParamOrDefault(
            String key,
            String defaultValue);
    /**
     * <pre>
     * 用户自定义参数
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_param = 5;</code>
     */

    String getCustomParamOrThrow(
            String key);
  }
  /**
   * <pre>
   * 请求Header
   * </pre>
   *
   * Protobuf type {@code codec.RequestHeader}
   */
  public  static final class RequestHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:codec.RequestHeader)
      RequestHeaderOrBuilder {
    // Use RequestHeader.newBuilder() to construct.
    private RequestHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestHeader() {
      serviceName_ = "";
      methodName_ = "";
      callId_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              serviceName_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              methodName_ = s;
              break;
            }
            case 24: {

              callId_ = input.readUInt64();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                customParam_ = com.google.protobuf.MapField.newMapField(
                    CustomParamDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<String, String>
              customParam__ = input.readMessage(
                  CustomParamDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              customParam_.getMutableMap().put(
                  customParam__.getKey(), customParam__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RPCHeader.internal_static_codec_RequestHeader_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetCustomParam();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RPCHeader.internal_static_codec_RequestHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RPCHeader.RequestHeader.class, RPCHeader.RequestHeader.Builder.class);
    }

    private int bitField0_;
    public static final int SERVICE_NAME_FIELD_NUMBER = 1;
    private volatile Object serviceName_;
    /**
     * <pre>
     * 服务名或接口名
     * </pre>
     *
     * <code>optional string service_name = 1;</code>
     */
    public String getServiceName() {
      Object ref = serviceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 服务名或接口名
     * </pre>
     *
     * <code>optional string service_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      Object ref = serviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_NAME_FIELD_NUMBER = 2;
    private volatile Object methodName_;
    /**
     * <pre>
     * 方法名
     * </pre>
     *
     * <code>optional string method_name = 2;</code>
     */
    public String getMethodName() {
      Object ref = methodName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 方法名
     * </pre>
     *
     * <code>optional string method_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      Object ref = methodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CALL_ID_FIELD_NUMBER = 3;
    private long callId_;
    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>optional uint64 call_id = 3;</code>
     */
    public long getCallId() {
      return callId_;
    }

    public static final int CUSTOM_PARAM_FIELD_NUMBER = 5;
    private static final class CustomParamDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  RPCHeader.internal_static_codec_RequestHeader_CustomParamEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        String, String> customParam_;
    private com.google.protobuf.MapField<String, String>
    internalGetCustomParam() {
      if (customParam_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CustomParamDefaultEntryHolder.defaultEntry);
      }
      return customParam_;
    }

    public int getCustomParamCount() {
      return internalGetCustomParam().getMap().size();
    }
    /**
     * <pre>
     * 用户自定义参数
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_param = 5;</code>
     */

    public boolean containsCustomParam(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetCustomParam().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCustomParamMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getCustomParam() {
      return getCustomParamMap();
    }
    /**
     * <pre>
     * 用户自定义参数
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_param = 5;</code>
     */

    public java.util.Map<String, String> getCustomParamMap() {
      return internalGetCustomParam().getMap();
    }
    /**
     * <pre>
     * 用户自定义参数
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_param = 5;</code>
     */

    public String getCustomParamOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetCustomParam().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 用户自定义参数
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_param = 5;</code>
     */

    public String getCustomParamOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetCustomParam().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getServiceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceName_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, methodName_);
      }
      if (callId_ != 0L) {
        output.writeUInt64(3, callId_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetCustomParam(),
          CustomParamDefaultEntryHolder.defaultEntry,
          5);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getServiceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serviceName_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, methodName_);
      }
      if (callId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, callId_);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetCustomParam().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        customParam__ = CustomParamDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, customParam__);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RPCHeader.RequestHeader)) {
        return super.equals(obj);
      }
      RPCHeader.RequestHeader other = (RPCHeader.RequestHeader) obj;

      boolean result = true;
      result = result && getServiceName()
          .equals(other.getServiceName());
      result = result && getMethodName()
          .equals(other.getMethodName());
      result = result && (getCallId()
          == other.getCallId());
      result = result && internalGetCustomParam().equals(
          other.internalGetCustomParam());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SERVICE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getServiceName().hashCode();
      hash = (37 * hash) + METHOD_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      hash = (37 * hash) + CALL_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCallId());
      if (!internalGetCustomParam().getMap().isEmpty()) {
        hash = (37 * hash) + CUSTOM_PARAM_FIELD_NUMBER;
        hash = (53 * hash) + internalGetCustomParam().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RPCHeader.RequestHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RPCHeader.RequestHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RPCHeader.RequestHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RPCHeader.RequestHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RPCHeader.RequestHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RPCHeader.RequestHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RPCHeader.RequestHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RPCHeader.RequestHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RPCHeader.RequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RPCHeader.RequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RPCHeader.RequestHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 请求Header
     * </pre>
     *
     * Protobuf type {@code codec.RequestHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:codec.RequestHeader)
        RPCHeader.RequestHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RPCHeader.internal_static_codec_RequestHeader_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetCustomParam();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableCustomParam();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RPCHeader.internal_static_codec_RequestHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RPCHeader.RequestHeader.class, RPCHeader.RequestHeader.Builder.class);
      }

      // Construct using com.zirtia.rpc.protocol.RPCHeader.RequestHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serviceName_ = "";

        methodName_ = "";

        callId_ = 0L;

        internalGetMutableCustomParam().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RPCHeader.internal_static_codec_RequestHeader_descriptor;
      }

      public RPCHeader.RequestHeader getDefaultInstanceForType() {
        return RPCHeader.RequestHeader.getDefaultInstance();
      }

      public RPCHeader.RequestHeader build() {
        RPCHeader.RequestHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RPCHeader.RequestHeader buildPartial() {
        RPCHeader.RequestHeader result = new RPCHeader.RequestHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.serviceName_ = serviceName_;
        result.methodName_ = methodName_;
        result.callId_ = callId_;
        result.customParam_ = internalGetCustomParam();
        result.customParam_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RPCHeader.RequestHeader) {
          return mergeFrom((RPCHeader.RequestHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RPCHeader.RequestHeader other) {
        if (other == RPCHeader.RequestHeader.getDefaultInstance()) return this;
        if (!other.getServiceName().isEmpty()) {
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          onChanged();
        }
        if (other.getCallId() != 0L) {
          setCallId(other.getCallId());
        }
        internalGetMutableCustomParam().mergeFrom(
            other.internalGetCustomParam());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RPCHeader.RequestHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RPCHeader.RequestHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object serviceName_ = "";
      /**
       * <pre>
       * 服务名或接口名
       * </pre>
       *
       * <code>optional string service_name = 1;</code>
       */
      public String getServiceName() {
        Object ref = serviceName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 服务名或接口名
       * </pre>
       *
       * <code>optional string service_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 服务名或接口名
       * </pre>
       *
       * <code>optional string service_name = 1;</code>
       */
      public Builder setServiceName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务名或接口名
       * </pre>
       *
       * <code>optional string service_name = 1;</code>
       */
      public Builder clearServiceName() {

        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务名或接口名
       * </pre>
       *
       * <code>optional string service_name = 1;</code>
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        serviceName_ = value;
        onChanged();
        return this;
      }

      private Object methodName_ = "";
      /**
       * <pre>
       * 方法名
       * </pre>
       *
       * <code>optional string method_name = 2;</code>
       */
      public String getMethodName() {
        Object ref = methodName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 方法名
       * </pre>
       *
       * <code>optional string method_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 方法名
       * </pre>
       *
       * <code>optional string method_name = 2;</code>
       */
      public Builder setMethodName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 方法名
       * </pre>
       *
       * <code>optional string method_name = 2;</code>
       */
      public Builder clearMethodName() {

        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 方法名
       * </pre>
       *
       * <code>optional string method_name = 2;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        methodName_ = value;
        onChanged();
        return this;
      }

      private long callId_ ;
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>optional uint64 call_id = 3;</code>
       */
      public long getCallId() {
        return callId_;
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>optional uint64 call_id = 3;</code>
       */
      public Builder setCallId(long value) {

        callId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>optional uint64 call_id = 3;</code>
       */
      public Builder clearCallId() {

        callId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> customParam_;
      private com.google.protobuf.MapField<String, String>
      internalGetCustomParam() {
        if (customParam_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              CustomParamDefaultEntryHolder.defaultEntry);
        }
        return customParam_;
      }
      private com.google.protobuf.MapField<String, String>
      internalGetMutableCustomParam() {
        onChanged();;
        if (customParam_ == null) {
          customParam_ = com.google.protobuf.MapField.newMapField(
              CustomParamDefaultEntryHolder.defaultEntry);
        }
        if (!customParam_.isMutable()) {
          customParam_ = customParam_.copy();
        }
        return customParam_;
      }

      public int getCustomParamCount() {
        return internalGetCustomParam().getMap().size();
      }
      /**
       * <pre>
       * 用户自定义参数
       * </pre>
       *
       * <code>map&lt;string, string&gt; custom_param = 5;</code>
       */

      public boolean containsCustomParam(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetCustomParam().getMap().containsKey(key);
      }
      /**
       * Use {@link #getCustomParamMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getCustomParam() {
        return getCustomParamMap();
      }
      /**
       * <pre>
       * 用户自定义参数
       * </pre>
       *
       * <code>map&lt;string, string&gt; custom_param = 5;</code>
       */

      public java.util.Map<String, String> getCustomParamMap() {
        return internalGetCustomParam().getMap();
      }
      /**
       * <pre>
       * 用户自定义参数
       * </pre>
       *
       * <code>map&lt;string, string&gt; custom_param = 5;</code>
       */

      public String getCustomParamOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetCustomParam().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * 用户自定义参数
       * </pre>
       *
       * <code>map&lt;string, string&gt; custom_param = 5;</code>
       */

      public String getCustomParamOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetCustomParam().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearCustomParam() {
        getMutableCustomParam().clear();
        return this;
      }
      /**
       * <pre>
       * 用户自定义参数
       * </pre>
       *
       * <code>map&lt;string, string&gt; custom_param = 5;</code>
       */

      public Builder removeCustomParam(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        getMutableCustomParam().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
      getMutableCustomParam() {
        return internalGetMutableCustomParam().getMutableMap();
      }
      /**
       * <pre>
       * 用户自定义参数
       * </pre>
       *
       * <code>map&lt;string, string&gt; custom_param = 5;</code>
       */
      public Builder putCustomParam(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        getMutableCustomParam().put(key, value);
        return this;
      }
      /**
       * <pre>
       * 用户自定义参数
       * </pre>
       *
       * <code>map&lt;string, string&gt; custom_param = 5;</code>
       */

      public Builder putAllCustomParam(
          java.util.Map<String, String> values) {
        getMutableCustomParam().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:codec.RequestHeader)
    }

    // @@protoc_insertion_point(class_scope:codec.RequestHeader)
    private static final RPCHeader.RequestHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RPCHeader.RequestHeader();
    }

    public static RPCHeader.RequestHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestHeader>
        PARSER = new com.google.protobuf.AbstractParser<RequestHeader>() {
      public RequestHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestHeader> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RequestHeader> getParserForType() {
      return PARSER;
    }

    public RPCHeader.RequestHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:codec.ResponseHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 请求Id
     * </pre>
     *
     * <code>optional uint64 call_id = 1;</code>
     */
    long getCallId();

    /**
     * <pre>
     * 返回码，0：成功，1：失败
     * </pre>
     *
     * <code>optional .codec.ResCode res_code = 2;</code>
     */
    int getResCodeValue();
    /**
     * <pre>
     * 返回码，0：成功，1：失败
     * </pre>
     *
     * <code>optional .codec.ResCode res_code = 2;</code>
     */
    RPCHeader.ResCode getResCode();

    /**
     * <pre>
     * 返回失败时的错误消息
     * </pre>
     *
     * <code>optional string res_msg = 3;</code>
     */
    String getResMsg();
    /**
     * <pre>
     * 返回失败时的错误消息
     * </pre>
     *
     * <code>optional string res_msg = 3;</code>
     */
    com.google.protobuf.ByteString
        getResMsgBytes();
  }
  /**
   * <pre>
   * 响应Header
   * </pre>
   *
   * Protobuf type {@code codec.ResponseHeader}
   */
  public  static final class ResponseHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:codec.ResponseHeader)
      ResponseHeaderOrBuilder {
    // Use ResponseHeader.newBuilder() to construct.
    private ResponseHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseHeader() {
      callId_ = 0L;
      resCode_ = 0;
      resMsg_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              callId_ = input.readUInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              resCode_ = rawValue;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              resMsg_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RPCHeader.internal_static_codec_ResponseHeader_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RPCHeader.internal_static_codec_ResponseHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RPCHeader.ResponseHeader.class, RPCHeader.ResponseHeader.Builder.class);
    }

    public static final int CALL_ID_FIELD_NUMBER = 1;
    private long callId_;
    /**
     * <pre>
     * 请求Id
     * </pre>
     *
     * <code>optional uint64 call_id = 1;</code>
     */
    public long getCallId() {
      return callId_;
    }

    public static final int RES_CODE_FIELD_NUMBER = 2;
    private int resCode_;
    /**
     * <pre>
     * 返回码，0：成功，1：失败
     * </pre>
     *
     * <code>optional .codec.ResCode res_code = 2;</code>
     */
    public int getResCodeValue() {
      return resCode_;
    }
    /**
     * <pre>
     * 返回码，0：成功，1：失败
     * </pre>
     *
     * <code>optional .codec.ResCode res_code = 2;</code>
     */
    public RPCHeader.ResCode getResCode() {
      RPCHeader.ResCode result = RPCHeader.ResCode.valueOf(resCode_);
      return result == null ? RPCHeader.ResCode.UNRECOGNIZED : result;
    }

    public static final int RES_MSG_FIELD_NUMBER = 3;
    private volatile Object resMsg_;
    /**
     * <pre>
     * 返回失败时的错误消息
     * </pre>
     *
     * <code>optional string res_msg = 3;</code>
     */
    public String getResMsg() {
      Object ref = resMsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        resMsg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 返回失败时的错误消息
     * </pre>
     *
     * <code>optional string res_msg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getResMsgBytes() {
      Object ref = resMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        resMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (callId_ != 0L) {
        output.writeUInt64(1, callId_);
      }
      if (resCode_ != RPCHeader.ResCode.RES_SUCCESS.getNumber()) {
        output.writeEnum(2, resCode_);
      }
      if (!getResMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, resMsg_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (callId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, callId_);
      }
      if (resCode_ != RPCHeader.ResCode.RES_SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, resCode_);
      }
      if (!getResMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, resMsg_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RPCHeader.ResponseHeader)) {
        return super.equals(obj);
      }
      RPCHeader.ResponseHeader other = (RPCHeader.ResponseHeader) obj;

      boolean result = true;
      result = result && (getCallId()
          == other.getCallId());
      result = result && resCode_ == other.resCode_;
      result = result && getResMsg()
          .equals(other.getResMsg());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CALL_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCallId());
      hash = (37 * hash) + RES_CODE_FIELD_NUMBER;
      hash = (53 * hash) + resCode_;
      hash = (37 * hash) + RES_MSG_FIELD_NUMBER;
      hash = (53 * hash) + getResMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RPCHeader.ResponseHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RPCHeader.ResponseHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RPCHeader.ResponseHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RPCHeader.ResponseHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RPCHeader.ResponseHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RPCHeader.ResponseHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RPCHeader.ResponseHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RPCHeader.ResponseHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RPCHeader.ResponseHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RPCHeader.ResponseHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RPCHeader.ResponseHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 响应Header
     * </pre>
     *
     * Protobuf type {@code codec.ResponseHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:codec.ResponseHeader)
        RPCHeader.ResponseHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RPCHeader.internal_static_codec_ResponseHeader_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RPCHeader.internal_static_codec_ResponseHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RPCHeader.ResponseHeader.class, RPCHeader.ResponseHeader.Builder.class);
      }

      // Construct using com.zirtia.rpc.protocol.RPCHeader.ResponseHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        callId_ = 0L;

        resCode_ = 0;

        resMsg_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RPCHeader.internal_static_codec_ResponseHeader_descriptor;
      }

      public RPCHeader.ResponseHeader getDefaultInstanceForType() {
        return RPCHeader.ResponseHeader.getDefaultInstance();
      }

      public RPCHeader.ResponseHeader build() {
        RPCHeader.ResponseHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RPCHeader.ResponseHeader buildPartial() {
        RPCHeader.ResponseHeader result = new RPCHeader.ResponseHeader(this);
        result.callId_ = callId_;
        result.resCode_ = resCode_;
        result.resMsg_ = resMsg_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RPCHeader.ResponseHeader) {
          return mergeFrom((RPCHeader.ResponseHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RPCHeader.ResponseHeader other) {
        if (other == RPCHeader.ResponseHeader.getDefaultInstance()) return this;
        if (other.getCallId() != 0L) {
          setCallId(other.getCallId());
        }
        if (other.resCode_ != 0) {
          setResCodeValue(other.getResCodeValue());
        }
        if (!other.getResMsg().isEmpty()) {
          resMsg_ = other.resMsg_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RPCHeader.ResponseHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RPCHeader.ResponseHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long callId_ ;
      /**
       * <pre>
       * 请求Id
       * </pre>
       *
       * <code>optional uint64 call_id = 1;</code>
       */
      public long getCallId() {
        return callId_;
      }
      /**
       * <pre>
       * 请求Id
       * </pre>
       *
       * <code>optional uint64 call_id = 1;</code>
       */
      public Builder setCallId(long value) {

        callId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求Id
       * </pre>
       *
       * <code>optional uint64 call_id = 1;</code>
       */
      public Builder clearCallId() {

        callId_ = 0L;
        onChanged();
        return this;
      }

      private int resCode_ = 0;
      /**
       * <pre>
       * 返回码，0：成功，1：失败
       * </pre>
       *
       * <code>optional .codec.ResCode res_code = 2;</code>
       */
      public int getResCodeValue() {
        return resCode_;
      }
      /**
       * <pre>
       * 返回码，0：成功，1：失败
       * </pre>
       *
       * <code>optional .codec.ResCode res_code = 2;</code>
       */
      public Builder setResCodeValue(int value) {
        resCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回码，0：成功，1：失败
       * </pre>
       *
       * <code>optional .codec.ResCode res_code = 2;</code>
       */
      public RPCHeader.ResCode getResCode() {
        RPCHeader.ResCode result = RPCHeader.ResCode.valueOf(resCode_);
        return result == null ? RPCHeader.ResCode.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 返回码，0：成功，1：失败
       * </pre>
       *
       * <code>optional .codec.ResCode res_code = 2;</code>
       */
      public Builder setResCode(RPCHeader.ResCode value) {
        if (value == null) {
          throw new NullPointerException();
        }

        resCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回码，0：成功，1：失败
       * </pre>
       *
       * <code>optional .codec.ResCode res_code = 2;</code>
       */
      public Builder clearResCode() {

        resCode_ = 0;
        onChanged();
        return this;
      }

      private Object resMsg_ = "";
      /**
       * <pre>
       * 返回失败时的错误消息
       * </pre>
       *
       * <code>optional string res_msg = 3;</code>
       */
      public String getResMsg() {
        Object ref = resMsg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          resMsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 返回失败时的错误消息
       * </pre>
       *
       * <code>optional string res_msg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getResMsgBytes() {
        Object ref = resMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          resMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 返回失败时的错误消息
       * </pre>
       *
       * <code>optional string res_msg = 3;</code>
       */
      public Builder setResMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        resMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回失败时的错误消息
       * </pre>
       *
       * <code>optional string res_msg = 3;</code>
       */
      public Builder clearResMsg() {

        resMsg_ = getDefaultInstance().getResMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回失败时的错误消息
       * </pre>
       *
       * <code>optional string res_msg = 3;</code>
       */
      public Builder setResMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        resMsg_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:codec.ResponseHeader)
    }

    // @@protoc_insertion_point(class_scope:codec.ResponseHeader)
    private static final RPCHeader.ResponseHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RPCHeader.ResponseHeader();
    }

    public static RPCHeader.ResponseHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseHeader>
        PARSER = new com.google.protobuf.AbstractParser<ResponseHeader>() {
      public ResponseHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseHeader> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ResponseHeader> getParserForType() {
      return PARSER;
    }

    public RPCHeader.ResponseHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codec_RequestHeader_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_codec_RequestHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codec_RequestHeader_CustomParamEntry_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_codec_RequestHeader_CustomParamEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_codec_ResponseHeader_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_codec_ResponseHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020rpc_header.proto\022\005codec\"\274\001\n\rRequestHea" +
      "der\022\024\n\014service_name\030\001 \001(\t\022\023\n\013method_name" +
      "\030\002 \001(\t\022\017\n\007call_id\030\003 \001(\004\022;\n\014custom_param\030" +
      "\005 \003(\0132%.codec.RequestHeader.CustomParamE" +
      "ntry\0322\n\020CustomParamEntry\022\013\n\003key\030\001 \001(\t\022\r\n" +
      "\005value\030\002 \001(\t:\0028\001\"T\n\016ResponseHeader\022\017\n\007ca" +
      "ll_id\030\001 \001(\004\022 \n\010res_code\030\002 \001(\0162\016.codec.Re" +
      "sCode\022\017\n\007res_msg\030\003 \001(\t*(\n\007ResCode\022\017\n\013RES" +
      "_SUCCESS\020\000\022\014\n\010RES_FAIL\020\001B$\n\027com.zirtia.r" +
      "pc.protocolB\tRPCHeaderb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_codec_RequestHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_codec_RequestHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_codec_RequestHeader_descriptor,
        new String[] { "ServiceName", "MethodName", "CallId", "CustomParam", });
    internal_static_codec_RequestHeader_CustomParamEntry_descriptor =
      internal_static_codec_RequestHeader_descriptor.getNestedTypes().get(0);
    internal_static_codec_RequestHeader_CustomParamEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_codec_RequestHeader_CustomParamEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_codec_ResponseHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_codec_ResponseHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_codec_ResponseHeader_descriptor,
        new String[] { "CallId", "ResCode", "ResMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
